
version: '3.7'
services:
    postgres:
        container_name : ignite-database-queries
        image: postgres:13
        restart: always
        ports:
          - 5432:5432
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - TZ=America/Sao_paulo
          - PGTZ=America/Sao_paulo